# Generated by Django 3.0.2 on 2020-01-08 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('doneTime', models.DateTimeField()),
                ('custom', models.BooleanField()),
                ('duration', models.BooleanField()),
                ('difficulty', models.IntegerField()),
                ('length', models.FloatField()),
                ('effortType', models.IntegerField()),
                ('completion', models.FloatField()),
                ('userPk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
