# Generated by Django 3.0.2 on 2020-01-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='duration',
            field=models.DurationField(),
        ),
    ]
